products:
  - founders_edition:
    title: The Founders Edition
    url: https://shaarkoo.com/products/the-founders-edition
    images: 
      - assets\products\essential\IMG-2457.jpg
      - assets\products\essential\IMG_1875_1.jpeg
    short_description: The Founders Edition comes with a walnut charcuterie board and 3 gorgeous custom templates!
  - bonus_pack_one:
    title: Template Pack One
    url: https://shaarkoo.com/products/the-founders-edition
    images: 
      - assets\products\essential\IMG-2457.jpg
      - assets\products\essential\IMG_1875_1.jpeg
    short_description: More templates